version: '3.8'

services:
  backend:
    image: raghadisraghad/express-recipe
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/Recipes
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    image: raghadisraghad/angular-recipe
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
    driver: local
